project:
  type: website
  output-dir: docs

website:
  title: "UAGV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - team.qmd
      - statement.qmd
      - partnership.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

